import { Employee } from "../models/Employee.js";
import { User } from "../models/User.js";
import { Op } from "sequelize";
import bcrypt from "bcrypt";
import employeeCacheService from "../services/employeeCacheService.js";

export const getAllEmployees = async (req, res) => {
    try {
        // Get store_id from query params (for SM/SUP filtering)
        const { store_id } = req.query;
        
        let whereClause = {};
        
        // If store_id is provided, filter by store (for SM/SUP)
        if (store_id) {
            whereClause.store_id = store_id;
        }
        
        // Always exclude HQ employees
        whereClause.role = { [Op.ne]: 'HQ' };
        
        const employees = await Employee.findAll({
            where: whereClause,
            order: [['created_at', 'DESC']]
        });
        
        res.json(employees);
    } catch (error) {
        console.error("Lỗi khi lấy danh sách nhân viên:", error);
        res.status(500).json({ message: 'Get All Error', error: error.message });
    }
};

export const getEmployeeById = async (req, res) => {
    try {
        const employee = await Employee.findByPk(req.params.id);
        !employee
            ? res.status(404).json({ message: "Không tìm thấy nhân viên" })
            : res.status(200).json(employee);
    }
    catch (error) {
        console.error("Lỗi lấy nhân viên:", error);
        res.status(500).json({ message: 'GetById Error', error: error.message });
    }
};

export const getEmployeeBySeacrh = async (req, res) => {
    try {
        const { keyword } = req.query;
        const employees = await Employee.findAll({
            where: {
                [Op.or]: [
                { full_name: { [Op.iLike]: `%${keyword}%` } },
                { phone: { [Op.iLike]: `%${keyword}%` } },
                { employee_id: { [Op.iLike]: `%${keyword}%` } }
            ]
        },
        order: [['full_name', 'DESC']]
        });
        if (employees.length === 0) {
            return res.status(404).json({ message: "Không tìm thấy nhân viên nào"});
        }
        res.status(200).json(employees);
    }
    catch (error) {
        console.error("Lỗi khi tìm kiếm nhân viên:", error);
        res.status(500).json({ message: 'Search Error', error: error.message });
    }
};

export const createEmployee = async (req, res) => {
    const transaction = await Employee.sequelize.transaction();
    
    try {
        const { full_name, phone, role, type, base_salary, hourly_rate, contract_end, username, password } = req.body;

        // Validate role - only allow CREW, CREW_TRAINER, CREW_LEADER, SUP for branch employees
        const allowedRoles = ['CREW', 'CREW_TRAINER', 'CREW_LEADER', 'SUP'];
        if (role && !allowedRoles.includes(role)) {
            return res.status(400).json({ message: "Chức vụ không hợp lệ cho nhân viên chi nhánh" });
        }

        // Validate salary based on type
        if (type === "full-time" && (!base_salary || base_salary === "")) {
            return res.status(400).json({ message: "Nhân viên full-time phải có lương cơ bản" });
        }
        if (type === "part-time" && (!hourly_rate || hourly_rate === "")) {
            return res.status(400).json({ message: "Nhân viên part-time phải có lương theo giờ" });
        }

        // Create employee (employee_id will be auto-generated by database trigger)
        const employee = await Employee.create({
            full_name,
            phone,
            role: role || 'CREW',
            type: type || 'part-time',
            base_salary: type === "full-time" ? base_salary : null,
            hourly_rate: type === "part-time" ? hourly_rate : null,
            contract_end: contract_end || null,
            active: true
        }, { transaction });

        // If username and password provided, create user account
        if (username && password) {
            // Check if username already exists
            const existingUser = await User.findOne({ where: { username } });
            if (existingUser) {
                await transaction.rollback();
                return res.status(400).json({ message: "Tên đăng nhập đã tồn tại" });
            }

            // Hash password
            const hashedPassword = await bcrypt.hash(password, 10);

            // Create user account linked to employee
            await User.create({
                employee_id: employee.id,
                username,
                password: hashedPassword,
                active: true
            }, { transaction });
        }

        // Commit transaction
        await transaction.commit();

        // Invalidate cache
        await employeeCacheService.invalidate();

        res.status(201).json({ 
            message: 'Nhân viên đã được thêm!',
            employee: {
                id: employee.id,
                employee_id: employee.employee_id,
                full_name: employee.full_name
            }
        });
    }
    catch (error) {
        await transaction.rollback();
        console.error("Lỗi khi thêm nhân viên:", error);
        res.status(500).json({ message: 'Create Error', error: error.message });
    }
};

export const updateEmployee = async (req, res) => {
    try {
        // Only allow updating these fields - NOT role (as per requirement)
        const { full_name, phone, type, base_salary, hourly_rate, contract_end } = req.body;
        
        const [updatedEmployee] = await Employee.update(
            { 
                full_name, 
                phone, 
                type, 
                base_salary, 
                hourly_rate, 
                contract_end
            },
            { where: { id: req.params.id },
            returning: true }
        );
        
        if(updatedEmployee === 0) {
            return res.status(404).json({ message: "Không tìm thấy nhân viên"});
        }

        // Invalidate cache
        await employeeCacheService.invalidate();

        res.status(200).json({ message: "Thông tin nhân viên đã được cập nhật!" });
    }
    catch (error) {
        console.error("Lỗi khi cập nhật nhân viên: ", error);
        res.status(500).json({ message: "Update Error", error: error.message });
    }
};

export const activeEmployee = async (req, res) => {
    try {
        const { active } = req.body;
        const [activedEmployee] = await Employee.update(
            { active },
            { where: { id: req.params.id } }
        );

        if(activedEmployee === 0) {
            return res.status(404).json({ message: "Không tìm thấy nhân viên"});
        }

        // Also update user account status if exists
        const employee = await Employee.findByPk(req.params.id);
        if (employee) {
            await User.update(
                { active },
                { where: { employee_id: employee.id } }
            );
        }

        // Invalidate cache
        await employeeCacheService.invalidate();

        return res.status(200).json({ message: "Đã cập nhật trạng thái nhân viên: " + (active ? "Kích hoạt" : "Vô hiệu hóa") });
    }
    catch (error) {
        console.error("Lỗi khi cập nhật nhân viên: ", error);
        res.status(500).json({ message: "Update Error", error: error.message });
    }
};

export const salaryEmployee = async (req, res) => {
    try {
        const { hourly_rate } = req.body;
        const [salaryedEmployee] = await Employee.update(
            { hourly_rate },
            { where: { id: req.params.id } }
        );
        if(salaryedEmployee === 0) {
            return res.status(404).json({ message: "Không tìm thấy nhân viên"});
        }

        // Invalidate cache
        await employeeCacheService.invalidate();

        res.status(200).json({ message: "Lương nhân viên đã được cập nhật!" });
    }
    catch (error) {
        console.error("Lỗi khi cập nhật nhân viên: ", error);
        res.status(500).json({ message: "Update Error", error: error.message });
    }
};

export const deleteEmployee = async (req, res) => {
    try {
        const deletedEmployee = await Employee.destroy({
            where: { id: req.params.id }
        });

        if (deletedEmployee === 0) {
            return res.status(404).json({ message: "Không tìm thấy nhân viên" });
        }

        // Invalidate cache
        await employeeCacheService.invalidate();

        res.status(200).json({ message: "Nhân viên đã được xóa!" });
    }
    catch (error) {
        console.error("Lỗi khi xóa nhân viên: ", error);
        res.status(500).json({ message: "Delete Error", error: error.message });
    }
};

