name: CI/CD Docker for Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  docker-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t backend-image ./backend

      - name: Run container
        run: |
          docker run -d -p 3000:3000 \
            --name backend-test-container \
            -e DATABASE_URL="${{ secrets.DATABASE_URL_TEST }}" \
            -e NODE_ENV="test" \
            -e OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:4318" \
            backend-image
          echo "Đang đợi 30s để Backend kết nối DB Aiven và khởi động..."
          sleep 30

      - name: Health check & Debug logs
        run: |
          # Gọi đúng endpoint /health đã tạo hoặc gọi thử route auth nếu chưa tạo /health
          if ! curl -f http://localhost:3000/health; then
            echo "❌ Health check thất bại! Đang kiểm tra log..."
            docker logs backend-test-container
            exit 1
          else
            echo "✅ Backend đã sẵn sàng kết nối!"
          fi

      - name: Stop and cleanup container
        run: docker rm -f backend-test-container

      - name: Trigger Render Deploy
        if: success()
        run: |
          echo "Test Backend thành công! Đang gọi Render..."
          curl -f -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL_BACKEND }}"